site_name: The CaRCC AI Facilitation Handbook
docs_dir: handbook
nav:
  - Authors & Acknowledgements: authors.md
  - Introduction: index.md
  - Problem Definition & Planning: problem-definition.md
  - Data Preparation: data-preparation.md
  - Model Selection & Development: model-selection.md
  - Model Training & Tuning: model-training.md
  - Benchmarking, QC & Optimization: benchmarking.md
  - Model Application: model-application.md
  - Results & Reporting: results-reporting.md
  - Cross-Cutting Considerations: cross-cutting.md
  - Resources: resources.md
  - Contributing: contributing.md
repo_url: https://github.com/CaRCC/CaRCC-AI-Facilitation-Handbook
repo_name: CaRCC/CaRCC-AI-Facilitation-Handbook
theme:
  name: material
markdown_extensions:
  - footnotes
plugins:
  - search
  - bibtex:
      bib_file: refs.bib
      bib_by_default: true
